language: node_js

node_js:
  - "12.4"

install:
  - yarn install

script:
  - yarn run test:unit
  - yarn run test:e2e
  - yarn run build

branches:
  only:
    - master

notifications:
  email: false

deploy:
  provider: heroku
  on:
    repo: DrewFrost/javascript30
  api_key:
    secure: siWlHOX0T3HHDGdPTmzLgro+TwoqJBOH346AwWxTJyIXHHCchvyUPgsk9Qiw5iZHYpEDfrOPwHiBFAdZ/2AwnwhLUQWpe3LRlTNc9e34PtebnlfiyFZAJpa/Zqya19bqtvMrTpQ4ZBjmvLVN//Ecb2qH11QJJuD3GsaqhRwFtiajuJu8fRo9a7pRKFAjoie7TWmA0Rb3jbxCEfYHzK+ZR7iPrX4IVGXnQbV8Lr8wBotI5BeJirRv8/4OjnrBAJl0DnJZqZtBRRtzbU1jk8uN0Svvktj3a0u2uQsFdpO439anFtgYZqPxY0zhBXqNLST/vd5D9Z756UGo26dLJlYbkKUp2sFfKYbrUyGb20yk09qrVhPFkwWZOivE7kQm643oSH6Ffz3a8LEmeKKTU1im/VGLhEGWIq3sdK9/8FAbbsasL1nmkroaftQ4LdsZHAINk3XSurUC3NCmK19lTv8EXdc7xItnEjuHFQiUkU/7GbFS7GSDeL1TmDFJNoanDQEmHSoDrx6aoMi38T/nuhFaVOuEO9GLIXRh+Zz6Gb7ydo2EEakvrluy2K00SGsC/F+tT5X+HKSOtGYJDGlDrJChi5iT/y0H6p8Tbz9Waa/8eJ63OGTX3Kee70TkGAhkQiYLj4L5S9bl96lYF8mAZXh0ZT0fOuI9qrULrTHxY/fI7Pg=
  app: travis-javascript30
