language: node_js

node_js:
  - '12.4'

install:
  - yarn install

script:
  - yarn run test:unit
  - yarn run build

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - drew.vfrost@gmail.com
    on_success: always
    on_failure: always
