language: node_js

node_js:
  - "12.4"

install:
  - yarn install

script:
  - yarn run test:unit
  - yarn run build

branches:
  only:
    - master

deploy:
  provider: heroku
  on:
    repo: DrewFrost/javascript30
  api_key:
    secure: RUBvk4uE3Ucl9CNUO5wDQZbk9i+ogPuIjdMD2yjlmU3HSfZBgEI7osNIV/bA7rSmWj8uw9uMj1l++y/MwdAJN8Dp8ey4f9ufoJds8BqChsWA0Wn7dJShauyFBcISdFz1trz+KdMtSBri36kjYSOlFIq6/gZ5SIUwNgDmW7L2iPJwvdjZA6NlK6i++IHIJO8Q6TLxY9K47VrzfgQvKjri6urbtwacPA3N+oatQF8cZ6P76KB/x9n3XXGCuhyyQqmWhoIr9h4r1fi4Sye1w9ayDMhk5xNNJUzN8nge6Pqn6lwdmFN3NoPBpL8+kk5YwEqREU5qRlCBbARicnFM2aFkfmQxfvmWyaVjmIk4cgHCI33a2q7x95CuX5EmgsT5C8EwdrD1oKnDIsu+kcConmbVUL14r/Jv35ibVwEhvbDVPvXFRvGJTbr44Li/PuDofJLLuVtzFPhnDkkjLAF/LqVrpFMMT5IGW1uTSWLT1dZVcgeQmOwfaNIe5Wp0YWi3crBd/TK1kyBSDEAfnrGODu/PS60pXlrjGFiLec+yzjQ91UyDSqocjdHlgAE8/nB0SPwuSHiqHIYW3YjSyfC3yODFr/qy9rPRKcWPls9WZSII7sFYyCm4aAqYhMIGcZytTmGI3uj44iIjhfuymeBjVgg6QIh00NWsS/fDB5kJTYDtZZA=
  app: travis-javascript30
